CXEC-44999-Adyen migrate to Checkout API since Adyen no longer develo…
opf-postman/sap-commerce-cloud-open-payment-framework-integration pull request #12
Opened 2024-10-22 09:46 UTC by zeyun123

migrate to Checkout API since Adyen no longer develops the Classic API.

2024-10-22 12:51 UTC, rmcotton-sap approved these changes

2024-10-25 08:10 UTC, zeyun123 commented
for new commitment:
as discussed with Richard ,  the notification for refund and capture . the "success"field always be  "true", no matter refund ok or refund failed , so we should use "eventCode" to identify the result .

2024-10-25 08:31 UTC, rmcotton-sap approved these changes

2024-10-28 17:01 UTC, rmcotton-sap requested changes
we need to also apply the same change for the Hosted Fields integration regarding success:true issue.

2024-10-28 17:01 UTC, rmcotton-sap commented on postman/adyen/Hosted-Payment-Page/README.md
> +Since Adyen no longer develops or update old Classic API, OPF current only support Checkout API which Adyen suggested.
there is no need to document this. We have no existing customers and will just confuse talking about apis we no longer support.

2024-10-29 01:03 UTC, zeyun123 commented on postman/adyen/Hosted-Payment-Page/README.md
> +Since Adyen no longer develops or update old Classic API, OPF current only support Checkout API which Adyen suggested.
ok. I will revert this  NOTE

2024-10-29 03:23 UTC, merged